#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<time.h>

char inputChar()
{
    // TODO: rewrite this function
	int random;
	
	//an array of all 9 chars
	char array[] = {'[', '(', '{', ' ', 'a', 'x', '}', ')', ']'};
	
	//generate random number from 0~8
	random = rand() %9;
	
	//return the char at the random #
    return array[random];
}

char *inputString()
{
    // TODO: rewrite this function
	int i;
	int random;
	
	//an array of all 4 chars
	char array[] = {'r', 'e', 's', 't'};
	
	//allocate a memory string that holds 6 chars
	static char str[6];
	
	//loop through and assign the chars randomly to the str 
	for(i = 0; i < 6; i++)
	{
		//generate random # from 0~4
		random = rand()%4;
		
		//place the char from array at position generated by random into str
		str[i] = array[random];	
	}
	
	//place the \0 in to the last position of the str
	str[5] = '\0';
	
    return str;
}

void testme()
{
  int tcCount = 0;
  char *s;
  char c;
  int state = 0;
  while (1)
  {
    tcCount++;
    c = inputChar();
    s = inputString();
    printf("Iteration %d: c = %c, s = %s, state = %d\n", tcCount, c, s, state);

    if (c == '[' && state == 0) state = 1;
    if (c == '(' && state == 1) state = 2;
    if (c == '{' && state == 2) state = 3;
    if (c == ' '&& state == 3) state = 4;
    if (c == 'a' && state == 4) state = 5;
    if (c == 'x' && state == 5) state = 6;
    if (c == '}' && state == 6) state = 7;
    if (c == ')' && state == 7) state = 8;
    if (c == ']' && state == 8) state = 9;
    if (s[0] == 'r' && s[1] == 'e'
       && s[2] == 's' && s[3] == 'e'
       && s[4] == 't' && s[5] == '\0'
       && state == 9)
    {
      printf("error ");
      exit(200);
    }
  }
}


int main(int argc, char *argv[])
{
    srand(time(NULL));
    testme();
    return 0;
}
